apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:latest
        ports:
        - name: http
          containerPort: 3000
        - name: ssh
          containerPort: 22
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: GITEA__SERVER__DOMAIN
          value: "gitea.shjeon.kro.kr"
        - name: GITEA__SERVER__ROOT_URL
          value: "https://gitea.shjeon.kro.kr/"
        - name: GITEA__SERVER__SSH_DOMAIN
          value: "gitea.shjeon.kro.kr"
        - name: GITEA__SERVER__SSH_PORT
          value: "22"
        - name: GITEA__DATABASE__TYPE
          value: "sqlite3"
        volumeMounts:
        - name: gitea-data
          mountPath: /data
      volumes:
      - name: gitea-data
        persistentVolumeClaim:
          claimName: gitea-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  namespace: gitea
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: gitea
spec:
  selector:
    app: gitea
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-ingress
  namespace: gitea
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: gitea.shjeon.kro.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitea-service
            port:
              name: http
  tls:
  - hosts:
    - gitea.shjeon.kro.kr
    secretName: gitea-tls-secret # Traefik이 Let's Encrypt를 통해 생성할 시크릿 이름