apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-simple-config
  namespace: ingress-system
data:
  traefik.yaml: |
    # Entry Points
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"

    # API 설정
    api:
      dashboard: true
      insecure: false

    # 프로바이더 설정
    providers:
      kubernetescrd: {}
      kubernetesingress: {}

    # 로그 설정
    log:
      level: INFO

    # 메트릭 설정
    metrics:
      prometheus:
        addEntryPointsLabels: true
        addServicesLabels: true