apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-minimal
  namespace: ingress-system
data:
  traefik.yaml: |
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    
    providers:
      kubernetesingress: {}
    
    log:
      level: DEBUG