apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-calendar-backend
  namespace: date-calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: date-calendar-backend
  template:
    metadata:
      labels:
        app: date-calendar-backend
    spec:
      containers:
      - name: backend
        image: shjeon97/date-calendar-backend:latest
        ports:
        - containerPort: 4000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: date-calendar-backend-html
---
apiVersion: v1
kind: Service
metadata:
  name: date-calendar-backend
  namespace: date-calendar
spec:
  selector:
    app: date-calendar-backend
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: date-calendar-backend-html
  namespace: date-calendar
data:
  healthz.html: "OK"
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Date Calendar - Backend API</title>
        <meta charset="utf-8">
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .header { background: #6f42c1; color: white; padding: 20px; border-radius: 5px; }
            .content { margin: 20px 0; }
            .status { background: #28a745; color: white; padding: 10px; border-radius: 3px; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🔧 Date Calendar - Backend API</h1>
            <p>날짜 캘린더 시스템 백엔드 API</p>
        </div>
        <div class="content">
            <div class="status">✅ 백엔드 API 서비스가 정상적으로 작동 중입니다</div>
            <h3>API 정보:</h3>
            <ul>
                <li>서비스: date-calendar-backend</li>
                <li>포트: 4000</li>
                <li>네임스페이스: date-calendar</li>
                <li>API 엔드포인트: <a href="https://date-calendar.back-end.kro.kr">date-calendar.back-end.kro.kr</a></li>
                <li>프론트엔드: <a href="https://date-calendar.prod.kro.kr">date-calendar.prod.kro.kr</a></li>
            </ul>
        </div>
    </body>
    </html>