apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  destination:
    namespace: gitea
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitea
    repoURL: https://github.com/shjeon97/shjeon-services-infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true