apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: date-calendar
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shjeon97/shjeon-services-infrastructure
    targetRevision: HEAD
    path: applications/date-calendar
  destination:
    server: https://kubernetes.default.svc
    namespace: date-calendar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intranet
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shjeon97/shjeon-services-infrastructure
    targetRevision: HEAD
    path: applications/intranet
  destination:
    server: https://kubernetes.default.svc
    namespace: intranet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: live-connect
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shjeon97/shjeon-services-infrastructure
    targetRevision: HEAD
    path: applications/live-connect
  destination:
    server: https://kubernetes.default.svc
    namespace: live-connect
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pt-interview
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shjeon97/shjeon-services-infrastructure
    targetRevision: HEAD
    path: applications/pt-interview
  destination:
    server: https://kubernetes.default.svc
    namespace: pt-interview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true