apiVersion: v1
kind: Secret
metadata:
  name: exam-world-secrets
  namespace: exam-world
type: Opaque
data:
  db_password: c2hqZW9uMDUyOA==  # base64 encoded "shjeon0528"
  gmail_smtp_key: aGN4dXN2cW15b2ZuanNuZw==  # base64 encoded "hcxusvqmyofnjsng"