apiVersion: apps/v1
kind: Deployment
metadata:
  name: pt-interview-backend
  namespace: pt-interview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pt-interview-backend
  template:
    metadata:
      labels:
        app: pt-interview-backend
    spec:
      containers:
      - name: backend
        image: shjeon97/pt-interview-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          value: "shjeon.duckdns.org"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_NAME
          value: "pt-interview"
        - name: PORT
          value: "4000"
        - name: SERVER_ADDRESS
          value: "https://pt-interview.back-end.kro.kr"
        - name: GMAIL_SMTP_NAME
          value: "shjeon.dev@gmail.com"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pt-interview-secrets
              key: db_password
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: pt-interview-secrets
              key: private_key
        - name: GMAIL_SMTP_KEY
          valueFrom:
            secretKeyRef:
              name: pt-interview-secrets
              key: gmail_smtp_key
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        
---
apiVersion: v1
kind: Service
metadata:
  name: pt-interview-backend
  namespace: pt-interview
spec:
  selector:
    app: pt-interview-backend
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP